---
# Source: https://github.com/hendrikmaus/rust-workflows
#
# Continuous Integration Workflow For Rust
name: CI

# Define the triggers; usually merges to the repository
# default branch and pull-requests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # The following makes this workflow re-usable by other repositories
  # without having to copy the entire thing.
  # 
  # See https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  workflow_call: {}

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          components: rustfmt
          override: true
          profile: minimal
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          command: test

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          components: clippy
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - uses: actions-rs/clippy-check@9d09632661e31982c0be8af59aeb96b680641bc4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
